imports:
    - { resource: 'services.yml' }

parameters:
    api_test_url: 'https://test.api.dibspayment.eu'
    api_prod_url: 'https://api.dibspayment.eu'

    js_checkout_test_url: 'https://test.checkout.dibspayment.eu/v1/checkout.js?v=1'
    js_checkout_prod_url: 'https://checkout.dibspayment.eu/v1/checkout.js?v=1'

    supported_currencies: ['SEK', 'NOK', 'DKK']
    supported_countries: ['SWE', 'NOR', 'DNK']

    module_settings:
        configuration:
            DIBS_AWAITING_ORDER_STATE_ID: ~
            DIBS_ACCEPTED_ORDER_STATE_ID: ~
            DIBS_CANCELED_ORDER_STATE_ID: ~
            DIBS_REFUNDED_ORDER_STATE_ID: ~
            DIBS_COMPLETED_ORDER_STATE_ID: ~
            DIBS_MERCHANT_ID: ''
            DIBS_PROD_SECRET_KEY: ''
            DIBS_TEST_SECRET_KEY: ''
            DIBS_PROD_CHECKOUT_KEY: ''
            DIBS_TEST_CHECKOUT_KEY: ''
            DIBS_LANGUAGE: 'en-GB'
            DIBS_TEST_MODE: 1
            DIBS_SWEEDEN_ADDRESS_ID: ~
            DIBS_NORWAY_ADDRESS_ID: ~
            DIBS_DENMARK_ADDRESS_ID: ~

        order_states:
            - { name: 'Payment accepted in DIBS Easy', color: '#0094cf', paid: 1, invoice: 1, config: 'DIBS_ACCEPTED_ORDER_STATE_ID'}
            - { name: 'Payment completed in DIBS Easy', color: '#0094cf', paid: 1, invoice: 1, config: 'DIBS_COMPLETED_ORDER_STATE_ID'}
            - { name: 'Payment canceled in DIBS Easy', color: '#0094cf', paid: 0, invoice: 0, config: 'DIBS_CANCELED_ORDER_STATE_ID'}
            - { name: 'Payment refunded in DIBS Easy', color: '#0094cf', paid: 0, invoice: 1, config: 'DIBS_REFUNDED_ORDER_STATE_ID'}

        tabs:
            # "ParentClassName" key is deprecated in PS 1.7.2.x and kept only for compatability with PS 1.7.1.x
            - { name: 'DIBS Easy Checkout', class_name: 'AdminDibsConfiguration', parent_class_name: 'AdminParentPayment', ParentClassName: 'AdminParentPayment' }

        hooks:
            - 'actionFrontControllerSetMedia'
            - 'paymentOptions'
            - 'paymentReturn'
            - 'displayAdminOrder'
            - 'actionAdminControllerSetMedia'
            - 'actionOrderSlipAdd'
            - 'actionGetExtraMailTemplateVars'
            - 'actionObjectOrderAddAfter'
